builds:
  - main: ./cmd/cowsay/main.go
    env:
      - CGO_ENABLED=0
    ldflags: -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
  - main: ./cmd/cowthink/main.go
    env:
      - CGO_ENABLED=0
    ldflags: -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
archive:
  name_template: 'cowsay_{{ .Tag }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: 'cowsay_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
