builds:
  - id: cowsay
    main: ./cmd/cowsay/main.go
    binary: cowsay
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
      - goos: windows
        goarch: arm
        goarm: 7
  - id: cowthink
    main: ./cmd/cowthink/main.go
    binary: cowthink
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
      - goos: windows
        goarch: arm
        goarm: 7

archives:
- builds:
  - cowsay
  - cowthink
  name_template: 'cowsay_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
  files:
  - LICENSE
  - doc/cowsay.1

brews:
- name: neo-cowsay
  tap:
    owner: Code-Hex
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  homepage: "https://github.com/Code-Hex/Neo-cowsay"
  description: "Fast, funny, everyone wanted? new cowsay!!"
  folder: Formula
  install: |
    bin.install "cowsay"
    bin.install "cowthink"
    man1.install Dir["doc/cowsay.1"]

checksum:
  name_template: 'cowsay_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
