version: 2

variables:
  context: &context org-context
  working_directory: &working_directory /go/src/github.com/Code-Hex/Neo-cowsay
common_steps:
  restore_cache_modules: &restore_cache_modules
    keys:
      - go-mod-v1-{{ checksum "go.sum" }}

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: *working_directory
    steps:
      - checkout
      - restore_cache: *restore_cache_modules
      - run:
          name: Lint
          command: |
            go get golang.org/x/lint/golint
            make lint
      - run:
          name: Build
          command: make build
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
    
  release:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
    version: 2
    test-workflow:
      jobs:
        - build:
            context: *context
        - release:
            context: *context
            requires:
              - build
            filters:
              tags:
                only: /v[0-9]+\.[0-9]+\.[0-9]+/
              branches:
                ignore: /.*/
