on:
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Lint
      run: |
        go get golang.org/x/lint/golint
        export PATH="$PATH:$(go env GOPATH)/bin"
        make lint
      env:
        GO111MODULE: off
    - name: Run GoReleaser
      if: contains(github.ref, 'tags/v')
      uses: goreleaser/goreleaser-action@v1
      with:
        version: v0.123.3
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}