on:
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Lint
      run: |
        go get golang.org/x/lint/golint
        make lint
    - uses: taichi/approved-event-action@v1.2.1
      id: approved
      with:
        approvals: '1'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Cowsay LGTM
      uses: Code-Hex/neo-cowsay-action@v1
      if: steps.approved.outputs.approved == 'true'
      with:
        message: 'LGTM'
        cowsay_on_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run GoReleaser
      if: contains(github.ref, 'tags/v')
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}