on:
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: test
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup Go 1.17.2
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.2
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Vet
      run: make vet
    - name: Test
      run: make test
    - name: Lint
      run: |
        go get golang.org/x/lint/golint
        export PATH="$PATH:$(go env GOPATH)/bin"
        make lint
      env:
        GO111MODULE: off
    - name: Declare some variables
      id: vars
      run: |
        echo "::set-output name=coverage_txt::${RUNNER_TEMP}/coverage.txt"
    - name: Test Coverage (pkg)
      run: go test ./... -coverprofile=${{ steps.vars.outputs.coverage_txt }}
    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        files: ${{ steps.vars.outputs.coverage_txt }}